//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    using UnityEngine.SceneManagement;
    
    
    public class Game : TypedScene
    {
        
        private const string GUID = "16de81c2a91f9614582da49c79de8bae";
        
        public static void Load(GamePreset argument, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
        {
            LoadScene(GUID, loadSceneMode, argument);
        }
    }
}
